const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const menu=document.querySelector('#menu'),result=document.querySelector('#result');
const W=960,H=540,keys=new Set();let state='menu',difficulty='casual',shake=true,flash=false,sound=true;
let player,attacks=[],particles=[],warnings=[],elapsed=0,last=0,spawnClock=0,phase=0,screenFlash=0,shakePower=0,audio;
const phases=['THE EDGE','CROSS CUT','TEETH','FINAL VERDICT'];
const hpFor={low:18,casual:12,hard:6};

document.querySelectorAll('.segmented').forEach(group=>group.addEventListener('click',e=>{if(!e.target.matches('button'))return;group.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b===e.target));const v=e.target.dataset.value;if(group.id==='difficulty')difficulty=v;if(group.id==='shake')shake=v==='on';if(group.id==='flash')flash=v==='on'}));
document.querySelector('#start').onclick=start;document.querySelector('#again').onclick=()=>{result.classList.add('hidden');menu.classList.remove('hidden');state='menu'};
document.querySelector('#mute').onclick=e=>{sound=!sound;e.currentTarget.textContent=sound?'SOUND ON':'SOUND OFF'};
addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','x','X'].includes(e.key))e.preventDefault();keys.add(e.key.toLowerCase());if((e.key===' '||e.key.toLowerCase()==='x')&&state==='play')dash()});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));

function tone(freq=160,dur=.06,type='square',vol=.035){if(!sound)return;audio??=new AudioContext();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+dur);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+dur)}
function start(){menu.classList.add('hidden');state='play';elapsed=0;phase=0;spawnClock=0;attacks=[];warnings=[];particles=[];player={x:W/2,y:H*.78,r:9,hp:hpFor[difficulty],max:hpFor[difficulty],inv:0,dash:0,cool:0,trail:[]};tone(70,.5,'sawtooth',.05)}
function dash(){if(player.cool>0)return;player.dash=.2;player.inv=.42;player.cool=.72;tone(360,.11,'sawtooth',.045);for(let i=0;i<18;i++)particles.push({x:player.x,y:player.y,vx:(Math.random()-.5)*180,vy:(Math.random()-.5)*180,life:.45,c:'#43e9ff'})}
function hit(){if(player.inv>0)return;player.hp--;player.inv=1.05;screenFlash=flash?.12:.025;shakePower=shake?15:0;tone(65,.22,'sawtooth',.07);for(let i=0;i<28;i++)particles.push({x:player.x,y:player.y,vx:(Math.random()-.5)*260,vy:(Math.random()-.5)*260,life:.65,c:'#fff'});if(player.hp<=0)finish(false)}
function finish(win){state='end';document.querySelector('#result-kicker').textContent=win?'BATTLE COMPLETE':'THE KNIFE FALLS';document.querySelector('#result-title').textContent=win?'SURVIVED':'SHATTERED';document.querySelector('#result-copy').textContent=win?'You endured every phase of the Black Knife.':'Read the pink warnings, keep moving, and dash through the impossible cuts.';result.classList.remove('hidden');tone(win?620:55,.8,win?'sine':'sawtooth',.05)}
function lineAttack(angle,offset=0,delay=.72){warnings.push({kind:'line',angle,offset,life:delay,max:delay});setTimeout(()=>{if(state!=='play')return;attacks.push({kind:'line',angle,offset,life:.42,max:.42,w:13});shakePower=shake?7:0;tone(110,.15,'square',.035)},delay*1000)}
function tooth(side){const y=70+Math.random()*(H-140),left=side==='left';warnings.push({kind:'tooth',x:left?0:W,y,life:.55,max:.55});setTimeout(()=>{if(state!=='play')return;attacks.push({kind:'tooth',x:left?-70:W+70,y,vx:left?310:-310,life:3,r:30});tone(95,.1,'square')},550)}
function burst(){const cx=W/2,cy=H/2,n=14;for(let i=0;i<n;i++){const a=i/n*Math.PI*2+elapsed;attacks.push({kind:'orb',x:cx,y:cy,vx:Math.cos(a)*155,vy:Math.sin(a)*155,r:8,life:4})}tone(190,.15,'sawtooth')}
function spawn(dt){spawnClock-=dt;if(spawnClock>0)return;phase=Math.min(3,Math.floor(elapsed/15));if(phase===0){lineAttack(Math.random()*Math.PI,Math.random()*360-180);spawnClock=1.15}else if(phase===1){lineAttack((Math.random()>.5?1:-1)*.45,Math.random()*260-130,.55);if(Math.random()>.55)lineAttack(Math.PI/2+(Math.random()-.5)*.3,Math.random()*300-150,.55);spawnClock=.88}else if(phase===2){tooth(Math.random()>.5?'left':'right');if(Math.random()>.5)lineAttack(Math.random()*Math.PI,Math.random()*340-170,.5);spawnClock=.72}else{if(Math.random()>.42)burst();else{for(let i=0;i<3;i++)lineAttack(Math.random()*Math.PI,Math.random()*260-130,.48)}spawnClock=1.05}if(elapsed>=60)finish(true)}
function update(dt){if(state!=='play')return;elapsed+=dt;spawn(dt);let dx=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),dy=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);const mag=Math.hypot(dx,dy)||1,speed=player.dash>0?510:225;player.x=Math.max(15,Math.min(W-15,player.x+dx/mag*speed*dt));player.y=Math.max(42,Math.min(H-15,player.y+dy/mag*speed*dt));player.inv=Math.max(0,player.inv-dt);player.dash=Math.max(0,player.dash-dt);player.cool=Math.max(0,player.cool-dt);player.trail.unshift({x:player.x,y:player.y});player.trail=player.trail.slice(0,player.dash>0?12:4);warnings.forEach(a=>a.life-=dt);warnings=warnings.filter(a=>a.life>0);attacks.forEach(a=>{a.life-=dt;if(a.kind==='tooth'||a.kind==='orb'){a.x+=a.vx*dt;a.y+=(a.vy||0)*dt;if(Math.hypot(a.x-player.x,a.y-player.y)<a.r+player.r)hit()}else if(a.kind==='line'){const nx=-Math.sin(a.angle),ny=Math.cos(a.angle),dist=Math.abs((player.x-W/2)*nx+(player.y-H/2)*ny-a.offset);if(dist<a.w+player.r)hit()}});attacks=attacks.filter(a=>a.life>0);particles.forEach(p=>{p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.96;p.vy*=.96});particles=particles.filter(p=>p.life>0);screenFlash=Math.max(0,screenFlash-dt);shakePower*=.85}
function linePath(a,o){ctx.save();ctx.translate(W/2,H/2);ctx.rotate(a);ctx.beginPath();ctx.moveTo(-800,o);ctx.lineTo(800,o);ctx.restore()}
function draw(){ctx.save();if(shakePower>1)ctx.translate((Math.random()-.5)*shakePower,(Math.random()-.5)*shakePower);ctx.fillStyle='#050105';ctx.fillRect(-20,-20,W+40,H+40);ctx.fillStyle='#13030d';for(let i=0;i<55;i++){const x=(i*137)%W,y=(i*83)%H;ctx.fillRect(x,y,1,1)}
  if(state==='play'){ctx.fillStyle='#2a0920';ctx.fillRect(0,0,W,28);ctx.fillStyle='#ff176f';ctx.fillRect(0,0,W*Math.min(1,elapsed/60),3);ctx.font='bold 10px Space Mono';ctx.fillStyle='#fff';ctx.fillText(`${phases[phase]}  //  ${Math.max(0,60-elapsed).toFixed(1)}s`,18,19);ctx.textAlign='right';ctx.fillStyle='#c789ae';ctx.fillText(`DASH ${player.cool<=0?'READY':player.cool.toFixed(1)}`,W-18,19);ctx.textAlign='left';
  warnings.forEach(a=>{ctx.save();ctx.strokeStyle='#ff176f';ctx.globalAlpha=.2+.6*(1-a.life/a.max);ctx.lineWidth=2;ctx.setLineDash([10,10]);if(a.kind==='line'){linePath(a.angle,a.offset);ctx.stroke()}else{ctx.beginPath();ctx.moveTo(a.x,a.y-35);ctx.lineTo(a.x+(a.x? -1:1)*90,a.y);ctx.lineTo(a.x,a.y+35);ctx.stroke()}ctx.restore()});
  attacks.forEach(a=>{ctx.save();ctx.strokeStyle=ctx.fillStyle='#ff176f';ctx.shadowColor='#ff176f';ctx.shadowBlur=18;if(a.kind==='line'){ctx.globalAlpha=Math.min(1,a.life*6);ctx.lineWidth=a.w*2;linePath(a.angle,a.offset);ctx.stroke();ctx.lineWidth=2;ctx.strokeStyle='#fff';linePath(a.angle,a.offset);ctx.stroke()}else if(a.kind==='tooth'){ctx.translate(a.x,a.y);ctx.rotate(a.vx>0?0:Math.PI);ctx.beginPath();ctx.moveTo(-35,-28);ctx.lineTo(38,0);ctx.lineTo(-35,28);ctx.lineTo(-15,0);ctx.closePath();ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.stroke()}else{ctx.beginPath();ctx.arc(a.x,a.y,a.r,0,7);ctx.fill()}ctx.restore()});
  particles.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life*2);ctx.fillStyle=p.c;ctx.fillRect(p.x-2,p.y-2,4,4)});ctx.globalAlpha=1;player.trail.forEach((p,i)=>{ctx.fillStyle=`rgba(67,233,255,${.18-i*.012})`;ctx.beginPath();ctx.arc(p.x,p.y,Math.max(2,player.r-i*.45),0,7);ctx.fill()});ctx.save();ctx.translate(player.x,player.y);ctx.rotate(Math.PI/4);ctx.fillStyle=player.inv>0&&Math.floor(player.inv*14)%2?'#fff':'#43e9ff';ctx.shadowColor='#43e9ff';ctx.shadowBlur=18;const squash=player.dash>0?1.7:1;ctx.scale(squash,1/squash);ctx.fillRect(-player.r,-player.r,player.r*2,player.r*2);ctx.restore();
  const hpW=180;ctx.fillStyle='#2c1022';ctx.fillRect(18,H-24,hpW,7);ctx.fillStyle=player.hp/player.max<.3?'#ffe600':'#43e9ff';ctx.fillRect(18,H-24,hpW*player.hp/player.max,7);ctx.fillStyle='#fff';ctx.font='bold 9px Space Mono';ctx.fillText(`HP ${player.hp} / ${player.max}`,18,H-31)}
  ctx.restore();if(screenFlash>0){ctx.fillStyle=`rgba(255,255,255,${flash?.7:.18})`;ctx.fillRect(0,0,W,H)}}
function loop(t){const dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
